### ISSUE TITLE
Feature request: user can clear/deselect the date

### ISSUE THREAD

**Issue by martijnvermaat** [radubrehar/react-date-picker#8]
Many use cases would allow a date field to be empty. Starting from an `undefined` field works fine, but once a date is selected, there's no way to clear the selection anymore.

I'm not sure what the best UI for this would be. Probably an additional button in the footer, or by re-clicking the selected date?

**Comment by radubrehar** [comment]
Hi Martijn,

thanks for using the date picker. I gave a thought on your request, and indeed it is often needed to clear the selection.

But I suggest you use the controlled version of the date picker, I mean to specify `date` instead of `defaultDate`, and a code similar to the one below. In this way we avoid adding a new button, that some would not need, and you can add a "clear date" UI wherever you want.

```jsx
'use strict';
var DatePicker = require('react-date-picker')
var date = Date.now()
var App = React.createClass({

    render: function(){
        return <div>
            <DatePicker date={date} onChange={this.onChange} />
            <button onClick={this.onClear}>clear</button>
        </div>
    },

   onChange: function(value){
        date = value
        this.setState({})
   },

   onClear: function(){
        date = null
        this.setState({})
   }
})

React.render(<App />, document.body)
```

Hope it helps.
Radu

**Comment by martijnvermaat** [comment]
Hi Radu,

Thanks for the quick response. Indeed, this would also work, and for me that's good enough.

cheers,
Martijn
